import Head from "next/head";
import Image from "next/image";
import React, { FC, useEffect, useState } from "react";
import { makeStyles } from "@material-ui/core/styles";
import TextField from "@material-ui/core/TextField";

const useStyles = makeStyles((theme) => ({
  root: {
    "& > *": {
      margin: theme.spacing(1),
      width: "25ch",
    },
  },
}));

export default function Home() {
  const classes = useStyles();
  const [password, Setpassword] = useState("");
  const [name, Setname] = useState("");

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    console.log(e.target.value);
    Setname(e.target.value);
  };
  const handleInputPassword = (e: React.ChangeEvent<HTMLInputElement>) => {
    Setpassword(e.target.value);
  };
  const auth = async () => {
    const headers = {
      Accept: "application/json",
      "Content-Type": "application/json",
    };
    const body = {
      username: name,
      password: password,
    };
    try {
      const responseUserInfo = await fetch(
        `${process.env.REACT_APP_API_URL}/api/create/`,
        {
          method: "POST",
          body: JSON.stringify(body),
          headers: headers,
        }
      ).then((response) => response.json());
      console.log(responseUserInfo);
    } catch (err) {
      console.log(err);
    }
    try {
      const response = await fetch(
        `${process.env.REACT_APP_API_URL}/authen/jwt/create/`,
        {
          method: "POST",
          body: JSON.stringify(body),
          headers,
        }
      ).then((response) => {
        return response.json();
      });
      console.log(response);
    } catch (err) {
      console.log(err);
    }
  };
  return (
    <div className="min-h-screen py-0 px-2 flex flex-col justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hello World</h1>
      <form className={classes.root} noValidate autoComplete="off">
        <TextField
          id="standard-basic"
          label="ユーザー名"
          value={name}
          onChange={handleInputChange}
        />
        <TextField
          id="standard-basic"
          label="パスワード"
          onChange={handleInputPassword}
        />
      </form>

      <button onClick={auth}>認証</button>
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
